package org.ovi.network

enum class ErrorCodes {
    DATA_FORMAT_MISMATCH,
    UN_AUTHORIZED,
    BAD_INPUT,
    INPUT_OUTPUT_EXCEPTION,
    API_NOT_FOUND,
    INTERNAL_SERVER_ERROR,
    NETWORK_TIMEOUT_ERROR,
    NO_NETWORK,
    RESPONSE_FAILED_ERROR,
    UNKNOWN_ERROR,
    VALIDATIONS_ERROR,
    CONNECTION_ERROR,
}
